from golden_ratio_algorithm import find_min
from fibonacci_algorithm import find_min
from fibonacciStep import FibonacciStep
from goldenRatioStep import GoldenRatioStep
from constStep import ConstStep
