from golden_ratio_algorithm import find_min
from fibonacci_algorithm import find_min
from fibonacciStep import FibonacciStep
from goldenRatioStep import GoldenRatioStep
from splittingStep import SplittingStep
from constStep import ConstStep
import firstOrderOracle
